<?php
declare(strict_types=1);
require_once __DIR__.'/../src/ProductPolicy.php';
$checks=[];
function check(string $name,bool $pass): void { global $checks;$checks[]=['name'=>$name,'pass'=>$pass]; }
function rejects(callable $fn): bool { try{$fn();return false;}catch(InvalidArgumentException){return true;} }
$p=ProductPolicy::class;$now=200000;
check('Never seen is waiting',$p::connection(null,$now)['state']==='waiting');
check('Heartbeat exact 120 online',$p::connection($now-120,$now)['state']==='online');
check('Heartbeat 121 offline',$p::connection($now-121,$now)['state']==='offline');
check('Server clock reversal flagged',$p::connection($now+1,$now)['clock_anomaly']);
check('Missing reading',$p::reading(null,$now)['state']==='missing');
check('Future sample not fresh',$p::reading($now+1,$now)['state']==='clock_skew');
check('Exact sample boundary',$p::reading($now-120,$now)['state']==='fresh'&&$p::reading($now-121,$now)['state']==='stale');
foreach([59=>'59 detik lalu',60=>'1 menit lalu',3599=>'59 menit lalu',3600=>'1 jam lalu',86400=>'1 hari lalu'] as $age=>$label)check('Relative '.$age,$p::reading($now-$age,$now)['relative']===$label);
check('Pending expiry',$p::commandExpiry(100,null,3)===160);
check('ACK window minimum',$p::commandExpiry(100,110,3)===140);
check('ACK window duration + grace',$p::commandExpiry(100,110,30)===155);
check('Expiry equality rejects',$p::expired(160,160)&&!$p::expired(160,159)&&$p::expired(160,161));
foreach([0,-1,11,1.5,true,'3',null] as $v)check('Reject duration '.json_encode($v),rejects(fn()=>$p::feederDuration($v)));
check('Duration endpoints',$p::feederDuration(1)===1&&$p::feederDuration(10)===10);
$code=$p::activationCode();check('Code normalization',$p::normalizeCode(strtolower($code))===str_replace('-','',$code));
check('Alphabet no ambiguous',strpbrk($p::config()['ACTIVATION_ALPHABET'],'01ILO')===false);
check('Entropy alphabet cardinality',strlen($p::config()['ACTIVATION_ALPHABET'])===31);
check('Reject ambiguous',rejects(fn()=>$p::normalizeCode('OOOO-OOOO-OOOO-OOOO')));
check('Activation expiry boundary',!$p::expired($p::activationExpiry(100),2592099)&&$p::expired($p::activationExpiry(100),2592100));
$state=[];for($i=0;$i<4;$i++)$state=$p::activationFailure($state,100);
check('Four failures not locked',$p::retryAfter($state,100)===0);
$state=$p::activationFailure($state,100);check('Five failures locked',$p::retryAfter($state,100)===900);
check('Unlock exact boundary',$p::retryAfter($state,999)===1&&$p::retryAfter($state,1000)===0);
check('New failure window',$p::activationFailure($state,1000)['failures']===1);
$n=$p::notification([],true,100);check('First breach sends',$n['send']);
$n=$p::notification($n['state'],true,1000);check('Persistent breach never repeats',!$n['send']);
$n=$p::notification($n['state'],false,1001);$n=$p::notification($n['state'],false,1120);check('119 recovery not armed',!$n['state']['armed']);
$n=$p::notification($n['state'],true,1121);check('Flapping suppresses',!$n['send']&&$n['state']['recovery_since']===null);
$n=$p::notification($n['state'],false,1200);$n=$p::notification($n['state'],false,1320);check('120 recovery rearms',$n['state']['armed']);
$n=$p::notification($n['state'],true,1321);check('Recovered new episode sends',$n['send']);
$n=$p::notification($n['state'],false,1322);$n=$p::notification($n['state'],false,1442);
$n=$p::notification($n['state'],true,1620);check('299 cooldown suppresses',!$n['send']);
$n=$p::notification($n['state'],true,1621);check('300 cooldown permits',$n['send']);
$stamp=strtotime('2026-09-16T17:00:00Z');check('UTC midnight WIB',$p::localClock($stamp)->format('Y-m-d H:i')==='2026-09-17 00:00');
check('Occurrence stable after restart',$p::occurrenceKey('7',$stamp)===$p::occurrenceKey('7',$stamp+30));
check('Occurrence different next day',$p::occurrenceKey('7',$stamp)!==$p::occurrenceKey('7',$stamp+86400));
check('Window midnight inclusive',$p::pumpWindow('23:59','00:01',$stamp-60)&&$p::pumpWindow('23:59','00:01',$stamp));
check('Window end exclusive',!$p::pumpWindow('23:59','00:01',$stamp+60));
check('Reject ambiguous window',rejects(fn()=>$p::pumpWindow('00:00','00:00',$stamp)));
check('Reject invalid hour',rejects(fn()=>$p::minute('24:00'))&&rejects(fn()=>$p::minute('08:60')));
echo json_encode(['checks'=>$checks,'passed'=>!in_array(false,array_column($checks,'pass'),true)],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE).PHP_EOL;
exit(in_array(false,array_column($checks,'pass'),true)?1:0);
