<?php
declare(strict_types=1);

// Product-flow assumptions and their rationale: docs/KALKULASI.md.
return [
    'HEARTBEAT_FRESH_SECONDS' => 120,
    'READING_FRESH_SECONDS' => 120,
    'COMMAND_PENDING_SECONDS' => 60,
    'COMMAND_ACK_MIN_SECONDS' => 30,
    'COMMAND_ACK_GRACE_SECONDS' => 15,
    'PUSH_MIN_INTERVAL_SECONDS' => 300,
    'PUSH_RECOVERY_SECONDS' => 120,
    'ACTIVATION_ALPHABET' => 'ABCDEFGHJKMNPQRSTUVWXYZ23456789',
    'ACTIVATION_LENGTH' => 16,
    'ACTIVATION_GROUP_LENGTH' => 4,
    'ACTIVATION_TTL_SECONDS' => 2592000,
    'ACTIVATION_COLLISION_RETRIES' => 5,
    'ACTIVATION_MAX_FAILURES' => 5,
    'ACTIVATION_LOCK_SECONDS' => 900,
    'DEVICE_KEY_BYTES' => 32,
    'FEEDER_MIN_SECONDS' => 1,
    'FEEDER_MAX_SECONDS' => 10,
    'SCHEDULE_TIMEZONE' => 'Asia/Jakarta',
];
